### ISSUE TITLE
Support for React 16

### ISSUE THREAD

**Issue by tmcdonnell87** [TeamWertarbyte/material-ui-rating#12]
Thanks for the quick turnaround on https://github.com/TeamWertarbyte/material-ui-fullscreen-dialog/issues/14. Similarly, can we bump this to not throw a warning with React 16?

Thanks again for the great components!

**Comment by saschb2b** [comment]
There is already a next branch by installing it with `npm install material-ui-rating@next` That should just work with react 16 and material ui 1.0. Or do you mean react 16 for mui < 1.0 releases?

**Comment by saschb2b** [comment]
Version 1.4.1 does now has a peer dependency for react 16.
