### ISSUE TITLE
Support for half-stars

### ISSUE THREAD

**Issue by doomsower** [TeamWertarbyte/material-ui-rating#13]
This is a feature request.
Some other star rating components have ability to render rating to half-star precision, like so:
![example](https://camo.githubusercontent.com/ab327850215118f9be0f6ddcdc06e28de8bb1339/68747470733a2f2f696d672e616c6963646e2e636f6d2f7470732f544231696a6c704c565858585862385870585858585858585858582d3436362d3137322e706e67)

It would be nice to have this ability together with material-ui integration in one component.

**Comment by leMaik** [comment]
@doomsower Great idea, we'll look into this. :+1:

**Comment by bjm88** [comment]
I get this error trying to use.. does it support latest react and material ui versions?
./node_modules/material-ui-rating/lib/components/Rating/Rating.js
Module not found: Can't resolve 'material-ui/IconButton' in '/Users/ben/dev/mountsinai/MountSinaiConsumer/webui/node_modules/material-ui-rating/lib/components/Rating'

**Comment by saschb2b** [comment]
@bjm88 yes, it does. See the readme and use the next tag `npm install material-ui-rating@next` If you got further problems feel free to open an separate issue.

**Comment by pankajparkar** [comment]
@saschb2b  Updating to latest `material-ui-rating@next` version doesn't solved the issue. I'm getting below error.
`
./node_modules/material-ui-rating/lib/components/Rating/Rating.jsModule not found: Can't resolve 'material-ui-icons/Star' in '/Users/synerzip/Desktop/ArcadeCity/city-rideshare/node_modules/material-ui-rating/lib/components/Rating'`

**Comment by pankajparkar** [comment]
@saschb2b Updating to latest material-ui-rating@next version doesn't solved the issue. I'm getting below error.

```./node_modules/material-ui-rating/lib/components/Rating/Rating.jsModule not found: Can't resolve 'material-ui-icons/Star' in '/Users/synerzip/xxx/node_modules/material-ui-rating/lib/components/Rating'```

**Comment by leMaik** [comment]
@pankajparkar Yes, it's currently broken. I'll update this component asap, see #18

**Comment by leMaik** [comment]
Done and released in v3.1.0 :tada: Only took a year to implement. :see_no_evil:
