### ISSUE TITLE
Adding both className and iconClassName causes double rendering

### ISSUE THREAD

**Issue by RavenHursT** [TeamWertarbyte/material-ui-rating#16]
See it here: https://codesandbox.io/s/q95402151j

Also, why isn't there an option/way to set the `className` on the root `div` element?

**Comment by leMaik** [comment]
Thanks for reporting this, unfortunately this issue went off of our radar. :confused: I'll try to fix this; There is no way to set a `className` on the root div because we forgot about that. I'll fix that. :+1:

**Comment by leMaik** [comment]
This is an upstream "issue" due to the fact how `IconButton` works: `iconClassName` is only meant to be used with font icons. If you want to use font icons, you'll have to use the [Font Icon](http://www.material-ui.com/#/components/font-icon) element as `icon…` property.

**Comment by leMaik** [comment]
Well, at least I fixed the root className bug. :+1: It's a breaking change, unfortunately.
