### ISSUE TITLE
Errors with Material UI V 1.4.3

### ISSUE THREAD

**Issue by aneacolacao** [TeamWertarbyte/material-ui-rating#18]
I have the problem `./node_modules/material-ui-rating/lib/components/Rating/Rating.js
Module not found: Can't resolve 'material-ui/IconButton' in ` I changed some lines on Rating.js (updated material-ui calls to @material-ui/core/) and then a new error comes:
`TypeError: Cannot read property 'orange500' of undefined`

I'm using material-ui-rating V 2.0.0

**Comment by leMaik** [comment]
:scream: This went completely off of our radar. I'll fix it asap!
