### ISSUE TITLE
Adding typescript definitions (index.d.ts)

### ISSUE THREAD

**Issue by brauliodiez** [TeamWertarbyte/material-ui-rating#22]
I think this project has no typescript definitions, I think it could be of great help.

If you don't have bandwith to achieve this task, I can tackle on it.

**Comment by leMaik** [comment]
@brauliodiez Oh yes, PR welcome! :clap: 

Edit: I'd like to use the same approach as in [our other project](https://github.com/TeamWertarbyte/material-ui-chip-input).

**Comment by leMaik** [comment]
I added typings and released them in v4.1.0. Please raise a new issue if there's anything wrong with them.

**Comment by cmocanu** [comment]
Doesn't seem to work, I think you need to also upload a new package @types/material-ui-rating. This 4.1.0 btw.

```
➜  for_netlify tree node_modules/material-ui-rating
node_modules/material-ui-rating
├── LICENSE
├── README.md
├── lib
│   ├── components
│   │   └── Rating
│   │       ├── Rating.js
│   │       └── index.js
│   └── index.js
├── package.json
├── preview.gif
└── stories
    └── index.js

4 directories, 8 files
➜  for_netlify yarn info @types/material-ui-rating
yarn info v1.7.0
(node:56464) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fmaterial-ui-rating: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mac/Work/webdev/for_netlify/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/info for documentation about this command.
```

**Comment by crsanti** [comment]
It seems like types are not published. [There's a reference to `src` folder inside `package.json`](https://github.com/TeamWertarbyte/material-ui-rating/blob/v4.1.1/package.json#L6)

But neither `src/` nor `Rating.d.ts` is available as @cmocanu pointed out.
In order to expose the typings you should also include in `lib/` both
- `src/components/Rating/Rating.d.ts`
- `src/index.d.ts` (actually missing) and change the reference in package.json:
```diff
-"types": "src/index.d.ts",
+"types": "lib/index.d.ts",
```
