### ISSUE TITLE
Broken change with classes icon

### ISSUE THREAD

**Issue by gespispace** [TeamWertarbyte/material-ui-rating#23]
Hi 
In [commit](https://github.com/TeamWertarbyte/material-ui-rating/commit/427f4b943196af8ec1ae83a943d02c4f2fef30f7#diff-ee45f72452795d9c3dc4273b2179f76aL24) was broken change which don't mark how broken.

Icon classes don't work and now i can't set size for icon svg.

[Demo](https://codesandbox.io/s/18n6q9mqrl)

Also docs have old information [see code](https://mui.wertarbyte.com/#!/Rating/9)

I would like to return this opportunity.

**Comment by leMaik** [comment]
I dropped that class to make users use the icon renderers to customize icons, but I see that having a class for that simplifies customization in simple cases (like yours).

I'll update the docs soon.

**Comment by leMaik** [comment]
Fixed in 856d0df6a093ebef6c64fd80c27230fd2efd2848 (for v3) and 7ef6d1ce1890a330ed8aa03fe3f2620d01b19734 (for v4).

New versions were released accordingly (v3.1.1 and v4.0.0-beta.2).
