### ISSUE TITLE
react warning: nativeColor prop

### ISSUE THREAD

**Issue by goldylucks** [TeamWertarbyte/material-ui-rating#24]
hey guys great job with the package!

I'm using react `16.8.6` and I'm getting a warning (attached console screenshot). I'm PRing a fix, let me know if it's ok :)

![image](https://user-images.githubusercontent.com/6963212/58086249-f5421300-7bc6-11e9-9c78-23e16c25632b.png)

**Comment by leMaik** [comment]
Looks like you're using Material-UI v4 with material-ui-rating v3. Please use `npm i --save material-ui-rating@next`.

https://github.com/TeamWertarbyte/material-ui-rating/releases/tag/v4.0.0-beta.2
https://github.com/TeamWertarbyte/material-ui-rating/releases/tag/v4.0.0-beta.1

**Comment by goldylucks** [comment]
You're right, sorry for that :)
