### ISSUE TITLE
PR - pass component as props

### ISSUE THREAD

**Issue by goldylucks** [TeamWertarbyte/material-ui-rating#27]
following the MUI conventions, I'd like to pass `<Rating component="span" />`

I have a use case in which  `<Rating />` is nested within a `<p />` element, and I get a dom violation.

Shall I prepare a PR?

I can also add an example in `Rating.md`, and for story book I'd love some guidance since I've never done that before.

**Comment by leMaik** [comment]
PR welcome :+1: 

Regarding the examples: I'd say it's sufficient to add the property to the table in the readme, but maybe add a story, too, just to validate that everything still works with `component="span"`. You can start the storybook with `npm run storybook`, and add stories by adding a new `.add` call [here](https://github.com/TeamWertarbyte/material-ui-rating/blob/master/stories/index.js#L61).

Please let us know if you need any help. :upside_down_face:
