### ISSUE TITLE
PR - prettier / eslint

### ISSUE THREAD

**Issue by goldylucks** [TeamWertarbyte/material-ui-rating#30]
while working on #28 accidentally formatted many of the files automatically through prettier. I see there's no prettier nor eslint in the project. I can add it with the config of your choice, i.e. semistandard.

I think it will make it easier to maintain/extend.

Thoughts?

**Comment by leMaik** [comment]
We're already using standard linter, see [https://github.com/TeamWertarbyte/material-ui-rating/blob/master/package.json#L8](the package.json).

Is there any configuration we're missing?

**Comment by goldylucks** [comment]
ohh my bad, I'm used to lint running on precommit hook. Closing this, thanks for pointing that out!
