### ISSUE TITLE
rating stars with a slow connection

### ISSUE THREAD

**Issue by lisa-tw** [TeamWertarbyte/material-ui-rating#35]
When clicking on a star and moving the mouse away from it, it will be rendered as a hovered star. This happens with a slow connection. Is this intended behaviour?

You can try it out here: Click on a star and move the mouse away from it. The stars will only be renderer as filled stars when hovering over them again.

https://codesandbox.io/embed/zen-einstein-58c61

**Comment by leMaik** [comment]
You would need optimistic requests to prevent that delay, i.e. update the rating _before_ sending the request and undo the update if the request fails. That's out of scope for this library, though.
