### ISSUE TITLE
Half star rating icon off center

### ISSUE THREAD

**Issue by Krypt0r7** [TeamWertarbyte/material-ui-rating#38]
I added a rating in my react project with precision set to 0.5. "averageRating" is a state that is evaluated on render. Image shows how the star is a bit off.  Did I do anything wrong or is this a bug?

![image](https://user-images.githubusercontent.com/42541928/75982431-f1c61100-5ee6-11ea-8aa4-0c0e5315a2b8.png)

`<Rating precision={0.5} name="averageRating" value={averageRating} />`

**Comment by leMaik** [comment]
This would be a bug (but I can't reproduce it), but there is no `precision` prop in this component. Are you using [Material-UI's rating component](https://material-ui.com/components/rating/) instead? If so, please report the bug over there.
