### ISSUE TITLE
whether you will add "Half ratings, sizes, and accessibility" functionality to the library?

### ISSUE THREAD

**Issue by rinatsafin** [TeamWertarbyte/material-ui-rating#46]
I wanted to use your library as a customizable solution because our design expects it, and we cannot use the original package from the material ui library.
And so I created the component based on this file but with fixing type and re-work from Classic React Component to Functional Component, maybe it help to use in future, but I can't use it without the above mentioned functionality. =(
https://github.com/TeamWertarbyte/material-ui-rating/blob/master/src/components/Rating/Rating.js

Link to the library with hooks
https://drive.google.com/file/d/1jVOePLPnqDwnzofa7BCIBgOve099SNKf/view?usp=sharing

PS: I mean full support how the original component does it
https://material-ui.com/api/rating/#rating-api

**Comment by leMaik** [comment]
@rinatsafin Sounds great, PR welcome :+1: I don't have time to add half ratings, sizes and accessibility at the moment.

**Comment by rinatsafin** [comment]
@leMaik Have you already looked through my code so quickly?).

**Comment by leMaik** [comment]
I'm tempted to close this as "Won't fix" because Material-UI really has exactly what you need. Why can't you use that?

I didn't look at your code yet. If you want to work on this, please submit a Pull Request so I can review your code changes properly, instead of a Google Drive link.

**Comment by rinatsafin** [comment]
I don't know)) 

>I'm tempted to close this as "Won't fix" because Material-UI really has exactly what you need

we can't customize the rendering of the Material-UI rating, because so we wanted to do it with your library, but there aren't enough **indexes** it's the second parameter from handlers like (iconHoveredRenderer)  
I want them to work like on hover the same way as before setting the value with onChange to do what we want, that's why I went to your source code.
