### ISSUE TITLE
onChange() never triggered

### ISSUE THREAD

**Issue by goferito** [TeamWertarbyte/material-ui-rating#5]
I'm using this with webpack and [material-ui](http://www.material-ui.com) and the component shows up, the max and value properties work as expected, but the onChange function is never triggered. I have tried on Firefox and Chrome for Ubuntu.

**Comment by goferito** [comment]
Ok, following the src code I've discovered that it maps the `onChange()` to `onTouchTap()` and I was not including the `react-tap-event-plugin` module. 

I think it would be cool if it would still work without requiring that module (until react includes it by default, then it won't be a problem anymore)

**Comment by leMaik** [comment]
The `react-tap-event-plugin` is required by Material-UI <1.0.0 anyway at the moment, so we probably won't remove it for now.
