### ISSUE TITLE
Support for Material-UI 1.0

### ISSUE THREAD

**Issue by TeodorKolev** [TeamWertarbyte/material-ui-rating#9]
Not compatible with Material ui 1.0 beta. Produce error

**Comment by leMaik** [comment]
Material-UI 1.0 is a major version bump and contains several major breaking changes. We will update this component soon, pull requests are welcome. :+1:

**Comment by amilosmanli** [comment]
Any progress on this?

**Comment by leMaik** [comment]
@cyberlake [Yes](https://github.com/TeamWertarbyte/material-ui-rating/tree/next), please install the latest pre-release with `npm i --save material-ui-rating@next`

**Comment by leMaik** [comment]
@saschb2b I  guess this could be closed then, right? :thinking: Any features not ported yet?

**Comment by nexthor** [comment]
@leMaik this still showing the error: 

node_modules/material-ui-rating/lib/components/Rating/Rating.js
Module not found: Can't resolve 'material-ui/svg-icons/toggle/star'

this is with the @next package

**Comment by leMaik** [comment]
@nexthor Sorry, it's been a while. :disappointed: We'll update the library for the latest material-ui.

**Comment by leMaik** [comment]
@nexthor I can't reproduce this. You need material-ui@next and material-ui-rating@next. Or, if you don't use material-ui@next yet, then just use material-ui-rating@latest.
